services:
  backend:
    build:
      context: ./PythonEditor
      dockerfile: Dockerfile
    container_name: python-editor
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./PythonEditor/temp:/temp
    depends_on:
      - python_image_puller
      - node_image_puller
    environment:
      ASPNETCORE_ENVIRONMENT: "development"
      ASPNETCORE_URLS: "http://+:5000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - backend


  python_image_puller:
    image: python:3.11-slim
    container_name: python_image_puller
    entrypoint: ["true"]

  node_image_puller:
      image: node:20-slim
      container_name: node_image_puller
      entrypoint: ["true"]